### ISSUE TITLE
Read-only state change is not detected in already opened documents

### ISSUE THREAD

**Issue by jszymonek** [mrlacey/ClearlyEditable#14]
I am working the Perforce source control system, in which every file is kept as read-only until "checked out". I am also using a plugin which automatically checks out the file whenever I try to edit it.
ClearlyEditable does not change the background color after  the read-only flag is cleared by the other extension, and I find myself editing a writable file with red background. When I reopen the document, color returns to normal.
This small detail blocks me from using this otherwise genius extension.

**Comment by mrlacey** [comment]
This is an interesting situation.
I'll need to do some investigation as to how to best detect this within the extension.

**Comment by mrlacey** [comment]
I wasn't able to find an alternative way to recreate what Perforce was doing, but the latest release (v2.8) _should_ do a better job of updating when a file is edited. 
If it doesn't pick up the change as you start typing, it _should_ update the color as soon as the file is saved.
LMK if it doesn't.
