### ISSUE TITLE
Add support for linked files 

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/ClearlyEditable#3]
default to a pale blue color

**Comment by mrlacey** [comment]
need to be able to detect if the original and a linked version exists elsewhere too.
Is it better to look this up for each file or parse the whole solution once?
Caching will be necessary but will need to invalidate whenever a project is changed (not just saved).

**Comment by LaraSQP** [comment]
Came here to request this very feature.

If it is supposed to be working (pale blue color), it isn't for me (Version 16.11.4).

Thank you for this and so many other great extensions and their quite insightful source code.

**Comment by mrlacey** [comment]
Sorry for the delayed response. Recent illness has stopped me from working on anything but I hope to get to this eventually.

**Comment by LaraSQP** [comment]
Please do not worry.

Get well.

**Comment by mrlacey** [comment]
To be clear: The goal here is to detect documents that exist in more than one project in a solution. 
i.e. If there are 3 drop downs at the top of the document window, a document is considered "linked" if it has multiple entries in the leftmost dropdown.

![image](https://user-images.githubusercontent.com/189547/148661435-d2d267af-04f5-4871-9c49-81ade69eb4f6.png)
_Yes, I know this screenshot shows a project that can be compiled for different targets and that's not the same thing but it was what I had open when I created the image_

**Comment by LaraSQP** [comment]
Yes.

The file exists elsewhere and it is added to a project via the "Add Existing Item" dialog + "Add As Link"

**Comment by mrlacey** [comment]
> Yes.
> 
> The file exists elsewhere and it is added to a project via the "Add Existing Item" dialog + "Add As Link"

Aaah. I think that's actually a different thing.

I was trying to work out what my original intentions were when I created this issue.
Initially, I assumed it was about files that are linked into the project (so not necessarily on disk, where the project view would automatically suggest.)  But then I couldn't come up with a reason why I wanted to know that which warranted coloring the background of the editor.
Then I realized that what I do care about is when I link a file so that it can be compiled into two separate projects within the same solution. I want to be aware of this so that the coloring prompts me to think about the changes I'm making in light of the fact that the project will be compiled in different projects.

Am I missing something in terms of the value of coloring a linked file even if it is only used in a single project?
Should these be considered as two separate scenarios? That may or may not be colored the same?
Or is it that you only link files when they are used in separate projects but not necessarily in the same solution? (Of course, detecting if a file is used in another project--that isn't in the same solution--is beyond reasonable detection here.)

My concern in coloring every linked value (regardless of how many projects it's included in) is that it adds a lot of visual prominence and importance to something that may not be very important. (And I have quite a few projects where the structure in solution explorer doesn't match what's on disk.)

**Comment by LaraSQP** [comment]
The problem to be addressed, in my opinion, is precisely what you mention here (except the strikethrough):

> the coloring prompts me to think about the changes I'm making in light of the fact that the ~~project~~ **file** will be compiled in different projects

I propose a single coloring for the linked file and the coloring to only be visible in the project where the file is linked (versus in the original which should remain as is).

The distinction between projects in the same solution or in different ones seems unimportant so color all the same.

**Comment by mrlacey** [comment]
> The problem to be addressed, in my opinion, is precisely what you mention here (except the strikethrough):
> 
> > the coloring prompts me to think about the changes I'm making in light of the fact that the ~project~ **file** will be compiled in different projects

Good catch.
 
> I propose a single coloring for the linked file and the coloring to only be visible in the project where the file is linked (versus in the original which should remain as is).

How is it useful to only color it in one place when it will still be used in more than one?

> The distinction between projects in the same solution or in different ones seems unimportant so color all the same.

To detect if a file is used in another solution (rather than the one loaded) would require searching all solution files accessible on disk to look for uses, and that's not practical. The point is that I can't tell if a file is used in a solution other than the one loaded.

**Comment by LaraSQP** [comment]
The file should only be colored in the project where it is linked, not wherever the source project is.

The `csproj` of the project containing the linked file should have a `<Compile Include="..\path\file.cs" Link="otherpath\file.cs" />` inside an `<ItemGroup>` (or something like that)

**Comment by mrlacey** [comment]
> The file should only be colored in the project where it is linked, not wherever the source project is.
> 
> The `csproj` of the project containing the linked file should have a `<Compile Include="..\path\file.cs" Link="otherpath\file.cs" />` inside an `<ItemGroup>` (or something like that)

Ok. I'll look at implementing that.
It'll be good to get a version to experiment with, rather than just speculate on the options 😄

**Comment by LaraSQP** [comment]
Sounds great.

**Comment by mrlacey** [comment]
I've just added some very basic handling for this (in version 2.4) and that is now available from the marketplace.
For performance and simplicity reasons this works by asking Visual Studio if the file "is linked".
This can result in a file being indicated as linked if opened from one project where it's not linked, even if it is linked in another project elsewhere in the solution.
This is closer to what I originally proposed than what was asked for in https://github.com/mrlacey/ClearlyEditable/issues/3#issuecomment-1008458012

If, after using this version, it is still felt that different behavior is preferred, I could look at an "advanced version" but that would need to look at the contents of every project in the solution. Because of the frequency that VS checks for the color to use for the background color, this could have performance implications. This would be a big issue in solutions containing a large number of projects.

**Comment by LaraSQP** [comment]
Is there a vs2019 version with this feature planned?

**Comment by LaraSQP** [comment]
Works as expected in vs2022, btw.

Much appreciated.

**Comment by mrlacey** [comment]
> Is there a vs2019 version with this feature planned?

By default and unless requested, I'm only applying security patches to the 2019 versions of my extensions.
So, I'll consider this such a request.

**Comment by mrlacey** [comment]
VS 2019 version now updated.

If you have any problems, comments, or suggestions please raise a new issue.
If you love it, please [leave a rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.ClearlyEditable&ssr=false#review-details) or consider [sponsorship](https://github.com/sponsors/mrlacey)  :smile:
