### ISSUE TITLE
Make tag configurable

### ISSUE THREAD

**Issue by hkaiser** [mrlacey/ClearlyEditable#8]
It would be nice to be able to configure the tag that is used to identify auto-generated files (currently hard-coded to `<auto-generated>`).

**Comment by mrlacey** [comment]
yes. A good idea.

I thought about doing this but was waiting for someone else to think it would be useful.

**Comment by mrlacey** [comment]
I've just pushed a new version to the marketplace (v2.0) that allows for multiple values to be specified to indicate a generated file if it can't be determined by the filename/path.

**Comment by hkaiser** [comment]
Thanks! works like a charm!

**Comment by mrlacey** [comment]
> Thanks! works like a charm!

That's great to hear.
You can help spread the word (and help me feel better about spending time on this) by [leaving a review in the marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.ClearlyEditable&ssr=false#review-details) ;)
